topics = [
    # "Reasoning Large Language Models",
    # "LLM Post-Training",
    # "Chain of Thought",
    # "Retrieval Augmented Generation RAG",
    "Continual Learning",
    "Multi-Agent",
    "Tool Learning",
    "Multi-Step Reasoning",
    "Fine-Tuning",
    "Reinforcement Learning Large Language Models LLM",
    "LLM Based Agent",
    "In-Context Learning",
    "RLHF",
    "Pre-Training",
]
